query allTerminals {
  allTerminals {
    edges {
      node {
        city {
          code
          name
          sortOrder
          id
        }
        geoArea {
          code
          name
          sortOrder
          id
        }
        code
        name
        slug
        id
      }
    }
  }
}